### ISSUE TITLE
Auto-TOC Part2

### ISSUE THREAD

**Issue by K-Sato1995** [K-Sato1995/MyBlogFront#16]
# Overview 
There were things I didn't do when I did [auto-toc](https://github.com/K-Sato1995/MyBlogFront/pull/13).
This issue is for finishing it up/making it better.

# Todo
- [x] Option of only showing h1 tag.
- [ ] Add indentation to `h4+` tags.
- [ ] Refactoring in general (the code is a mess rn)
